(function initializeClientPortal(global) {
  'use strict';
  const auth = global.ZyntraClientAuth;
  const supabase = auth.client();
  const state = { context: null, projects: [], calendar: [], drafts: [], revisions: [], deliverables: [], invoices: [], notifications: [] };
  const content = document.getElementById('portal-content');
  const sidebar = document.getElementById('portal-sidebar');
  const modal = document.getElementById('portal-modal');
  const modalBody = document.getElementById('portal-modal-body');
  const toast = document.getElementById('portal-toast');
  let toastTimer = 0;
  let submittingRevision = false;

  function el(tag, className, text) { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; }
  function formatDate(value, includeTime) { if (!value) return 'Not set'; const date = new Date(value); return new Intl.DateTimeFormat('en-LK', { year: 'numeric', month: 'short', day: 'numeric', ...(includeTime ? { hour: 'numeric', minute: '2-digit' } : {}) }).format(date); }
  function formatMoney(value, currency) { return new Intl.NumberFormat('en-LK', { style: 'currency', currency: currency || 'LKR', maximumFractionDigits: 2 }).format(Number(value || 0)); }
  function projectName(id) { return state.projects.find(item => item.id === id)?.project_name || 'Project'; }
  function badge(text) { const lower = String(text || '').toLowerCase(); const className = lower.includes('paid') || lower.includes('approved') || lower.includes('completed') ? ' cp-badge--success' : lower.includes('overdue') || lower.includes('revision') ? ' cp-badge--danger' : lower.includes('waiting') || lower.includes('pending') ? ' cp-badge--warning' : ''; return el('span', 'cp-badge' + className, text || 'Unknown'); }
  function empty(text) { return el('div', 'cp-empty', text); }
  function showToast(message) { clearTimeout(toastTimer); toast.textContent = message; toast.classList.add('is-visible'); toastTimer = setTimeout(() => toast.classList.remove('is-visible'), 3000); }
  function showError() { showToast('Something went wrong. Please try again or contact Zyntra Studio.'); }
  function openModal(titleText, bodyNode) { modalBody.replaceChildren(); const title = el('h2', '', titleText); title.id = 'portal-modal-title'; modalBody.append(title, bodyNode); modal.hidden = false; modal.querySelector('.cp-modal-close').focus(); }
  function closeModal() { modal.hidden = true; modalBody.replaceChildren(); submittingRevision = false; }
  function button(label, className) { const node = el('button', 'cp-button ' + (className || 'cp-button--secondary'), label); node.type = 'button'; return node; }

  function showView(name) {
    document.querySelectorAll('[data-portal-view]').forEach(node => { node.hidden = node.dataset.portalView !== name; });
    document.querySelectorAll('[data-view]').forEach(node => node.classList.toggle('is-active', node.dataset.view === name));
    sidebar.classList.remove('is-open'); document.getElementById('portal-menu').setAttribute('aria-expanded', 'false');
    history.replaceState(null, '', '#' + name);
  }

  async function loadData() {
    const userId = state.context.user.id;
    const requests = [
      supabase.from('client_projects').select('*').eq('client_id', userId).eq('archived', false).order('created_at', { ascending: false }),
      supabase.from('content_calendar').select('*').eq('client_id', userId).order('scheduled_date'),
      supabase.from('project_drafts').select('*').eq('client_id', userId).order('uploaded_at', { ascending: false }),
      supabase.from('revision_requests').select('*').eq('client_id', userId).order('created_at', { ascending: false }),
      supabase.from('deliverables').select('*').eq('client_id', userId).order('uploaded_at', { ascending: false }),
      supabase.from('invoices').select('*').eq('client_id', userId).order('issue_date', { ascending: false }),
      supabase.from('portal_notifications').select('*').eq('client_id', userId).order('created_at', { ascending: false })
    ];
    const results = await Promise.all(requests);
    if (results.some(result => result.error)) throw new Error('Portal data failed to load.');
    [state.projects, state.calendar, state.drafts, state.revisions, state.deliverables, state.invoices, state.notifications] = results.map(result => result.data || []);
  }

  function renderOverview() {
    const active = state.projects.filter(item => item.status !== 'Completed');
    const pendingDrafts = state.drafts.filter(item => item.status === 'Awaiting Review').length;
    const openRevisions = state.revisions.filter(item => item.status !== 'Resolved').length;
    const upcoming = state.calendar.filter(item => new Date(item.scheduled_date) >= new Date()).length;
    const pendingAmount = state.invoices.filter(item => ['Pending', 'Partially Paid', 'Overdue'].includes(item.payment_status)).reduce((sum, item) => sum + Number(item.amount || 0), 0);
    const average = active.length ? Math.round(active.reduce((sum, item) => sum + Number(item.progress || 0), 0) / active.length) : 0;
    const stats = [['Active projects', active.length], ['Current progress', average + '%'], ['Pending approvals', pendingDrafts], ['Open revisions', openRevisions], ['Upcoming content', upcoming], ['Pending payments', formatMoney(pendingAmount)], ['Unread updates', state.notifications.filter(item => !item.read).length]];
    const grid = document.getElementById('overview-stats'); grid.replaceChildren();
    stats.forEach(item => { const card = el('article', 'cp-stat'); card.append(el('span', '', item[0]), el('strong', '', String(item[1]))); grid.appendChild(card); });
    const projects = document.getElementById('overview-projects'); projects.replaceChildren(); const list = el('ul', 'cp-list'); active.slice(0, 4).forEach(project => { const item = el('li', 'cp-list-item'); item.append(el('strong', '', project.project_name), el('span', '', project.status + ' · ' + project.progress + '% complete')); list.appendChild(item); }); projects.appendChild(list.childElementCount ? list : empty('No active projects.'));
    const notifications = document.getElementById('overview-notifications'); notifications.replaceChildren(); const nList = el('ul', 'cp-list'); state.notifications.slice(0, 5).forEach(notification => { const item = el('li', 'cp-list-item'); item.append(el('strong', '', notification.title), el('span', '', formatDate(notification.created_at, true))); nList.appendChild(item); }); notifications.appendChild(nList.childElementCount ? nList : empty('No notifications yet.'));
  }

  function renderProjects() {
    const grid = document.getElementById('projects-grid'); grid.replaceChildren();
    state.projects.forEach(project => { const card = el('article', 'cp-card'); card.append(badge(project.status), el('h3', '', project.project_name), el('p', '', project.description || project.service_type)); const progress = el('div', 'cp-progress'); const fill = el('i'); fill.style.width = Math.max(0, Math.min(100, project.progress)) + '%'; progress.appendChild(fill); const dates = el('div', 'cp-card-row'); dates.append(el('span', '', 'Start: ' + formatDate(project.start_date)), el('span', '', 'Due: ' + formatDate(project.due_date))); const action = button('View Project'); action.addEventListener('click', () => openProject(project)); card.append(progress, dates, badge(project.priority), action); grid.appendChild(card); });
    if (!grid.childElementCount) grid.appendChild(empty('No projects have been assigned yet.'));
  }

  function openProject(project) {
    const wrapper = el('div'); const meta = el('div', 'cp-card-meta'); meta.append(badge(project.status), badge(project.priority), el('span', 'cp-badge', project.progress + '% complete')); wrapper.append(el('p', '', project.description || 'No project description.'), meta);
    const related = [
      ['Calendar items', state.calendar.filter(item => item.project_id === project.id)],
      ['Drafts', state.drafts.filter(item => item.project_id === project.id)],
      ['Revision requests', state.revisions.filter(item => item.project_id === project.id)],
      ['Deliverables', state.deliverables.filter(item => item.project_id === project.id)],
      ['Invoices', state.invoices.filter(item => item.project_id === project.id)]
    ];
    const timeline = el('div', 'cp-timeline'); related.forEach(group => { const item = el('div', 'cp-timeline-item'); item.append(el('strong', '', group[0]), el('p', '', group[1].length + ' record' + (group[1].length === 1 ? '' : 's'))); timeline.appendChild(item); }); wrapper.appendChild(timeline); const support = button('Contact Support', 'cp-button--primary'); support.addEventListener('click', () => openSupport(project)); wrapper.appendChild(support); openModal(project.project_name, wrapper);
  }

  function filteredCalendar() { const month = document.getElementById('calendar-month').value, platform = document.getElementById('calendar-platform').value, status = document.getElementById('calendar-status').value; return state.calendar.filter(item => (!month || item.scheduled_date.slice(0, 7) === month) && (!platform || item.platform === platform) && (!status || item.status === status)); }
  function renderCalendar() {
    const monthInput = document.getElementById('calendar-month'); if (!monthInput.value) monthInput.value = new Date().toISOString().slice(0, 7);
    const items = filteredCalendar(); const [year, month] = monthInput.value.split('-').map(Number); const first = new Date(year, month - 1, 1); const start = new Date(year, month - 1, 1 - first.getDay()); const grid = document.getElementById('calendar-grid'); grid.replaceChildren(); ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(day => grid.appendChild(el('div', 'cp-calendar-head', day)));
    for (let index = 0; index < 42; index += 1) { const date = new Date(start); date.setDate(start.getDate() + index); const cell = el('div', 'cp-calendar-day' + (date.getMonth() !== month - 1 ? ' is-outside' : '')); cell.appendChild(el('span', '', String(date.getDate()))); items.filter(item => new Date(item.scheduled_date).toDateString() === date.toDateString()).forEach(item => cell.appendChild(el('span', 'cp-calendar-event', item.title))); grid.appendChild(cell); }
    const agenda = document.getElementById('calendar-agenda'); agenda.replaceChildren(); items.forEach(item => { const card = el('article', 'cp-card'); card.append(badge(item.status), el('h3', '', item.title), el('p', '', item.platform + ' · ' + item.content_type), el('div', 'cp-card-row', formatDate(item.scheduled_date, true))); agenda.appendChild(card); }); if (!agenda.childElementCount) agenda.appendChild(empty('No content matches these filters.'));
    const upcoming = document.getElementById('upcoming-content'); upcoming.replaceChildren(); const list = el('ul', 'cp-list'); state.calendar.filter(item => new Date(item.scheduled_date) >= new Date()).slice(0, 8).forEach(item => { const li = el('li', 'cp-list-item'); li.append(el('strong', '', item.title), el('span', '', item.platform + ' · ' + formatDate(item.scheduled_date, true) + ' · ' + item.status)); list.appendChild(li); }); upcoming.appendChild(list.childElementCount ? list : empty('No upcoming content.'));
  }

  function populateFilters() { const platform = document.getElementById('calendar-platform'), status = document.getElementById('calendar-status'); [...new Set(state.calendar.map(item => item.platform).filter(Boolean))].sort().forEach(value => platform.appendChild(new Option(value, value))); ['Planned','In Production','Ready for Review','Approved','Scheduled','Published'].forEach(value => status.appendChild(new Option(value, value))); }
  async function signedUrl(bucket, path, download) { const result = await supabase.storage.from(bucket).createSignedUrl(path, 60, download ? { download: true } : undefined); if (result.error) throw result.error; return result.data.signedUrl; }
  async function previewDraft(draft) { try { const url = await signedUrl('client-drafts', draft.storage_path, false); const wrapper = el('div'); let preview; if ((draft.file_type || '').startsWith('image/')) { preview = el('img'); preview.src = url; preview.alt = draft.title; preview.style.maxWidth = '100%'; } else if ((draft.file_type || '').startsWith('video/')) { preview = el('video'); preview.src = url; preview.controls = true; preview.style.width = '100%'; } else if (draft.file_type === 'application/pdf') { preview = el('iframe'); preview.src = url; preview.title = draft.title; preview.style.cssText = 'width:100%;height:65vh;border:0'; } else { const open = button('Open secure preview', 'cp-button--primary'); open.addEventListener('click', () => global.open(url, '_blank', 'noopener')); preview = open; } wrapper.appendChild(preview); openModal(draft.title, wrapper); } catch (error) { showError(); } }
  function renderDrafts() { const grid = document.getElementById('drafts-grid'); grid.replaceChildren(); state.drafts.forEach(draft => { const card = el('article', 'cp-card'); const preview = el('div', 'cp-draft-preview', (draft.file_type || 'File') + ' · Version ' + draft.version); const actions = el('div', 'cp-actions'); const view = button('Preview'); view.addEventListener('click', () => previewDraft(draft)); actions.appendChild(view); if (draft.status === 'Awaiting Review') { const approve = button('Approve', 'cp-button--primary'); approve.addEventListener('click', () => approveDraft(draft, approve)); const revise = button('Request Revision'); revise.addEventListener('click', () => revisionForm(draft)); actions.append(approve, revise); } card.append(preview, badge(draft.status), el('h3', '', draft.title), el('p', '', projectName(draft.project_id) + ' · ' + draft.file_name), actions); grid.appendChild(card); }); if (!grid.childElementCount) grid.appendChild(empty('No drafts are waiting for review.')); }
  async function approveDraft(draft, trigger) { if (!confirm('Approve this draft? This action confirms the current version.')) return; trigger.disabled = true; const result = await supabase.rpc('approve_own_draft', { target_draft_id: draft.id }); if (result.error) { trigger.disabled = false; showError(); return; } showToast('Draft approved.'); await refresh(); }
  function revisionForm(draft) { const form = el('form', 'cp-form'); const label = el('label', 'cp-field'); label.append(el('span', '', 'Revision message')); const textarea = el('textarea'); textarea.required = true; textarea.maxLength = 2000; label.appendChild(textarea); const submit = button('Submit Revision', 'cp-button--primary'); submit.type = 'submit'; const cancel = button('Cancel'); cancel.addEventListener('click', closeModal); const actions = el('div', 'cp-actions'); actions.append(submit, cancel); const status = el('p', 'cp-form-status'); form.append(label, actions, status); form.addEventListener('submit', async event => { event.preventDefault(); if (submittingRevision || !form.reportValidity()) return; submittingRevision = true; submit.disabled = true; const result = await supabase.from('revision_requests').insert({ draft_id: draft.id, project_id: draft.project_id, client_id: state.context.user.id, message: textarea.value.trim(), status: 'Open' }); if (result.error) { status.textContent = 'The revision request could not be submitted.'; status.classList.add('is-error'); submit.disabled = false; submittingRevision = false; return; } closeModal(); showToast('Revision request submitted.'); await refresh(); }); openModal('Request Revision', form); textarea.focus(); }
  function renderDeliverables() { const grid = document.getElementById('deliverables-grid'); grid.replaceChildren(); state.deliverables.forEach(file => { const card = el('article', 'cp-card'); card.append(el('span', 'cp-badge', 'Final file'), el('h3', '', file.title), el('p', '', projectName(file.project_id) + ' · ' + file.file_name), el('div', 'cp-card-row', formatBytes(file.file_size) + ' · ' + formatDate(file.uploaded_at))); const download = button('Secure Download', 'cp-button--primary'); download.addEventListener('click', async () => { download.disabled = true; try { const url = await signedUrl('client-deliverables', file.storage_path, true); global.open(url, '_blank', 'noopener'); showToast('Secure link created. It expires in 60 seconds.'); } catch (error) { showError(); } download.disabled = false; }); card.appendChild(download); grid.appendChild(card); }); if (!grid.childElementCount) grid.appendChild(empty('No final files are available yet.')); }
  function formatBytes(value) { const bytes = Number(value || 0); if (!bytes) return 'Size unavailable'; const units = ['B','KB','MB','GB']; const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return (bytes / Math.pow(1024, index)).toFixed(index ? 1 : 0) + ' ' + units[index]; }
  function renderInvoices() { const grid = document.getElementById('invoices-grid'); grid.replaceChildren(); state.invoices.forEach(invoice => { const card = el('article', 'cp-card'); card.append(badge(invoice.payment_status), el('h3', '', invoice.invoice_number), el('p', 'cp-money', formatMoney(invoice.amount, invoice.currency)), el('p', '', projectName(invoice.project_id) + ' · ' + (invoice.description || 'Invoice')), el('div', 'cp-card-row', 'Issued ' + formatDate(invoice.issue_date) + ' · Due ' + formatDate(invoice.due_date))); if (invoice.payment_date) card.appendChild(el('p', '', 'Paid ' + formatDate(invoice.payment_date))); if (invoice.receipt_storage_path) { const receipt = button('Download Receipt'); receipt.addEventListener('click', async () => { try { global.open(await signedUrl('client-documents', invoice.receipt_storage_path, true), '_blank', 'noopener'); } catch (error) { showError(); } }); card.appendChild(receipt); } grid.appendChild(card); }); if (!grid.childElementCount) grid.appendChild(empty('No invoice records are available.')); }
  function renderNotifications() { const list = document.getElementById('notifications-list'); list.replaceChildren(); state.notifications.forEach(notification => { const card = el('article', 'cp-card cp-notification' + (notification.read ? '' : ' is-unread')); card.append(el('h3', '', notification.title), el('p', '', notification.message), el('div', 'cp-card-row', formatDate(notification.created_at, true))); if (!notification.read) { const read = button('Mark as read'); read.addEventListener('click', async () => { const result = await supabase.from('portal_notifications').update({ read: true }).eq('id', notification.id); if (result.error) showError(); else { notification.read = true; renderNotifications(); renderOverview(); } }); card.appendChild(read); } list.appendChild(card); }); if (!list.childElementCount) list.appendChild(empty('No notifications.')); }
  function renderProfile() { const profile = state.context.profile; document.getElementById('profile-full-name').value = profile.full_name || ''; document.getElementById('profile-business-name').value = profile.business_name || ''; document.getElementById('profile-phone').value = profile.phone || ''; }
  function renderSupport() { const select = document.getElementById('support-project'); select.replaceChildren(); state.projects.forEach(project => select.appendChild(new Option(project.project_name, project.id))); if (!state.projects.length) select.appendChild(new Option('General support', '')); }
  function openSupport(project) { const selected = project || state.projects.find(item => item.id === document.getElementById('support-project').value); const message = selected ? ['Hello Zyntra Studio,','','I need assistance with my project: ' + selected.project_name + '.','','Client: ' + state.context.profile.full_name,'Project ID: ' + selected.id,'','Please contact me regarding this project.'].join('\n') : 'Hello Zyntra Studio,\n\nI need assistance with my client portal.\n\nClient: ' + state.context.profile.full_name; global.open('https://wa.me/94706004033?text=' + encodeURIComponent(message), '_blank', 'noopener'); }
  function renderAll() { document.getElementById('overview-welcome').textContent = 'Welcome, ' + (state.context.profile.full_name || 'Client') + '.'; document.getElementById('portal-client-name').textContent = state.context.profile.full_name || 'Client Portal'; document.getElementById('portal-business-name').textContent = state.context.profile.business_name || state.context.user.email; renderOverview(); renderProjects(); populateFilters(); renderCalendar(); renderDrafts(); renderDeliverables(); renderInvoices(); renderNotifications(); renderProfile(); renderSupport(); }
  async function refresh() { try { await loadData(); renderAll(); } catch (error) { showError(); } }

  document.querySelectorAll('[data-view]').forEach(node => node.addEventListener('click', () => showView(node.dataset.view)));
  document.querySelectorAll('[data-logout]').forEach(node => node.addEventListener('click', async () => { if (!confirm('Log out of the client portal?')) return; node.disabled = true; try { await auth.logout('client'); } catch (error) { node.disabled = false; showToast(auth.safeMessage(error, 'Logout failed. Please try again.')); } }));
  document.getElementById('portal-menu').addEventListener('click', function () { const open = sidebar.classList.toggle('is-open'); this.setAttribute('aria-expanded', String(open)); });
  modal.querySelector('.cp-modal-close').addEventListener('click', closeModal); modal.addEventListener('click', event => { if (event.target === modal) closeModal(); }); document.addEventListener('keydown', event => { if (event.key === 'Escape') { if (!modal.hidden) closeModal(); else sidebar.classList.remove('is-open'); } });
  ['calendar-month','calendar-platform','calendar-status'].forEach(id => document.getElementById(id).addEventListener('change', renderCalendar));
  document.getElementById('support-whatsapp').addEventListener('click', () => openSupport());
  document.getElementById('mark-all-read').addEventListener('click', async () => { const unread = state.notifications.filter(item => !item.read); if (!unread.length) return; const result = await supabase.from('portal_notifications').update({ read: true }).in('id', unread.map(item => item.id)); if (result.error) showError(); else { unread.forEach(item => { item.read = true; }); renderNotifications(); renderOverview(); } });
  document.getElementById('profile-form').addEventListener('submit', async event => { event.preventDefault(); const status = document.getElementById('profile-status'); const form = event.currentTarget; if (!form.reportValidity()) return; const result = await supabase.rpc('update_my_profile', { new_full_name: document.getElementById('profile-full-name').value.trim(), new_business_name: document.getElementById('profile-business-name').value.trim(), new_phone: document.getElementById('profile-phone').value.trim() }); if (result.error) { status.textContent = auth.safeMessage(result.error, 'Your profile could not be updated.'); status.classList.add('is-error'); } else { status.textContent = 'Profile updated.'; status.classList.remove('is-error'); state.context.profile = result.data; renderProfile(); } });

  (async function start() { const loading = document.getElementById('portal-loading'); try { const context = await auth.requireAccess('client'); if (!context) return; state.context = context; auth.watchProtectedSession('client'); await loadData(); loading.remove(); document.querySelectorAll('[data-portal-view]').forEach(node => { node.hidden = true; }); renderAll(); showView(location.hash.slice(1) || 'overview'); } catch (error) { loading.classList.add('cp-access-error'); loading.textContent = auth.safeMessage(error, 'Your portal could not be loaded. Please refresh or contact Zyntra Studio.'); } }());
}(window));
